
service: expense-tracker-1
frameworkVersion: '3'

plugins:
  - serverless-auto-swagger
  - serverless-offline


provider:
  name: aws
  runtime: nodejs14.x
  
functions:
  endpoint:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /pong
          method: get
          
  createExpenseHead:
    handler: src/functions/expenseHead.createExpenseHeadHandler
    events:
      - http:
          path: /create/expensehead
          method: post
          cors: true
  getExpenseHeadById:
    handler: src/functions/expenseHead.getExpenseHeadByIdHandler
    events:
      - http:
          path: /filter/expensehead/{id}
          method: get
          cors: true  
  getExpenseHeads:
    handler: src/functions/expenseHead.getExpenseHeadHandler
    events:
      - http:
          path: /filter/expenseheads
          method: get
          cors: true                  
  updateExpenseHeads:
    handler: src/functions/expenseHead.updateExpenseHeadHandler
    events:
      - http:
          path: /filter/expenseheads/{id}
          method: patch
          cors: true
  createExpenses:
    handler: src/functions/expenses.createExpensesHandler
    events:
      - http:
          path: /create/expense
          method: post
          cors: true
  getExpenseById:
    handler: src/functions/expenses.getExpenseByIdHandler
    events:
      - http:
          path: /filter/expense/{id}
          method: get
          cors: true 
  getExpenses:
    handler: src/functions/expenses.filterExpensesHandler
    events:
      - http:
          path: /filter/expenses
          method: get
          cors: true 
  updateExpenses:
    handler: src/functions/expenses.updateExpenseshandler
    events:
      - http:
          path: /filter/expenses/{id}
          method: patch
          cors: true    
  deleteExpenses:
    handler: src/functions/expenses.deleteExpensesHandler
    events:
      - http:
          path: /delete/expenses/{id}
          method: delete
          cors: true 
  deleteExpenseHead:
    handler: src/functions/expenseHead.deleteExpenseHandler
    events:
      - http:
          path: /delete/expenseHead/{id}
          method: delete
          cors: true                                            
                      