// this file was generated by serverless-auto-swagger
module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "expense-tracker-1",
    "version": "1"
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/pong": {
      "get": {
        "summary": "endpoint",
        "description": "",
        "operationId": "endpoint",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/create/expensehead": {
      "post": {
        "summary": "createExpenseHead",
        "description": "",
        "operationId": "createExpenseHead",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/filter/expensehead/{id}": {
      "get": {
        "summary": "getExpenseHeadById",
        "description": "",
        "operationId": "getExpenseHeadById",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/filter/expenseheads": {
      "get": {
        "summary": "getExpenseHeads",
        "description": "",
        "operationId": "getExpenseHeads",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/filter/expenseheads/{id}": {
      "patch": {
        "summary": "updateExpenseHeads",
        "description": "",
        "operationId": "updateExpenseHeads",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/create/expense": {
      "post": {
        "summary": "createExpenses",
        "description": "",
        "operationId": "createExpenses",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/filter/expense/{id}": {
      "get": {
        "summary": "getExpenseById",
        "description": "",
        "operationId": "getExpenseById",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/filter/expenses": {
      "get": {
        "summary": "getExpenses",
        "description": "",
        "operationId": "getExpenses",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/filter/expenses/{id}": {
      "patch": {
        "summary": "updateExpenses",
        "description": "",
        "operationId": "updateExpenses",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/delete/expenses/{id}": {
      "delete": {
        "summary": "deleteExpenses",
        "description": "",
        "operationId": "deleteExpenses",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/delete/expenseHead/{id}": {
      "delete": {
        "summary": "deleteExpenseHead",
        "description": "",
        "operationId": "deleteExpenseHead",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {}
};